### ISSUE TITLE
labeList 和saasId似乎可以去掉？track_info是否需要用户来填写

### ISSUE THREAD

**Issue by greggzj** [NotwoJack/sam-helper#1]
大佬你好，非常赞的项目，因为叮咚helper也用过，看到这个JAVA的samhelper顿时非常激动，想请教一下大佬：
1） UserConfig中的labelList和saasId是否可以去掉  （理由是参考了这各star数量还不错的[Sam buy](https://github.com/azhan1998/sam_buy/blob/main/sam_buyV2.py)
里面没有使用这两个参数，不知这两个参数的意义是啥？

2)  track_info我看大佬写死了，这个在[Sam buy](https://github.com/azhan1998/sam_buy/blob/main/sam_buyV2.py)里面被讨论过是需要用户自己设置的？ 我抓包看我的track_info和你的就不一样，不知道这个字段意义何在。。。求赐教

PS： 希望大佬持续更新啊，顶你一个!

**Comment by NotwoJack** [comment]
感谢你的支持
1）[Sam buy](https://github.com/azhan1998/sam_buy/blob/main/sam_buyV2.py) 这个作者是抓的app接口，我是抓的小程序接口，小程序使用的参数略有不同，简化许多。
2） track_info这个东西，似乎不影响下单，我还在测试。

**Comment by greggzj** [comment]
谢谢大佬，今天用其他城市试了下你的最新代码，track_info填写为"", 能够正常下单
