### ISSUE TITLE
跑了一下代码，然后就被风控了！

### ISSUE THREAD

**Issue by Highnoon8X** [NotwoJack/sam-helper#10]
很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设置的 策略阻断</h1><p class="text1">本页面为<span class="text-color">腾讯T-Sec Web应用防火墙(WAF)</span>默认提示页面，如有疑问请联系网站管理员并提供UUID信息</p><p class="text2">

**Comment by NotwoJack** [comment]
山姆的风控十分钟就解开了，无需担心
