### ISSUE TITLE
环境配置问题：有很多方法出错了，是我哪些插件没装吗？

### ISSUE THREAD

**Issue by wJDKnight** [NotwoJack/sam-helper#7]
我用eclipse，已经装了lombok插件，还是报了以下错误。是有什么其他插件还要装吗？

The method setQuantity(String) is undefined for the type GoodDto	Api.java	/sam-helper-main/src/main/java	line 301	Java Problem
The method setQuantity(String) is undefined for the type GoodDto	Api.java	/sam-helper-main/src/main/java	line 437	Java Problem
The method setSpuId(String) is undefined for the type GoodDto	Api.java	/sam-helper-main/src/main/java	line 300	Java Problem
The method setSpuId(String) is undefined for the type GoodDto	Api.java	/sam-helper-main/src/main/java	line 436	Java Problem
The method setStoreId(String) is undefined for the type GoodDto	Api.java	/sam-helper-main/src/main/java	line 302	Java Problem
The method setStoreId(String) is undefined for the type GoodDto	Api.java	/sam-helper-main/src/main/java	line 438	Java Problem
Unhandled exception type InterruptedException	Api.java	/sam-helper-main/src/main/java	line 53	Java Problem
Unhandled exception type MalformedURLException	Api.java	/sam-helper-main/src/main/java	line 51	Java Problem

**Comment by NotwoJack** [comment]
推荐使用idea，以及你要是不熟悉java推荐使用隔壁的go项目。
